<a href="https://colab.research.google.com/github/vijaikrish/Machine-Learning-course/blob/main/machine_learning_tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# arrary from a python list 

list1 = [2,4,6,8,10]
arr1 = np.array(list1)

In [ ]:
arr1

array([ 2,  4,  6,  8, 10])

In [ ]:
list1

[2, 4, 6, 8, 10]

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
type(list1)

list

In [ ]:
list1 +1


TypeError: ignored

In [ ]:
arr1 +1

array([ 3,  5,  7,  9, 11])

In [ ]:
list2 = [(9,0, 4,6), 
         (4,6,2,1)]
arr2 = np.array(list2)

In [ ]:
# float array

arr2 = np.array(list2, dtype = 'float')

In [ ]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [ ]:
arr3 = arr2.astype('int')

In [ ]:
arr3

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [ ]:
arr4 = np.array(list2, dtype ='bool')

In [ ]:
arr4

array([[ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
list2

[(9, 0, 4, 6), (4, 6, 2, 1)]

In [ ]:
# any type as an array

arr5 = np.array([2,2.5,6,'y'], dtype ='object')

In [ ]:
arr5

array([2, 2.5, 6, 'y'], dtype=object)

In [ ]:
list3 = arr5.tolist()

In [ ]:
type(list3)

list

In [ ]:
type(arr5)

numpy.ndarray

Array Dimensions 

In [ ]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr2.size

8

In [ ]:
arr2.dtype

dtype('float64')

In [ ]:
arr2.ndim

2

Reversing Rows and column

In [ ]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [ ]:
arr2[::-1]

array([[4., 6., 2., 1.],
       [9., 0., 4., 6.]])

In [ ]:
arr2[::-1, ::-1]

array([[1., 2., 6., 4.],
       [6., 4., 0., 9.]])